version: "3.6"
services:
  authors:
    image: authors
    container_name: bff-authors-service
    ports:
      - 8081:8081
#    networks:
#      - mynet
    depends_on:
      - zipkin
  books:
    image: books
    container_name: bff-books-service
    ports:
      - 8082:8082
#    networks:
#      - mynet
    depends_on:
      - zipkin
  web-sockets:
    image: web-sockets
    container_name: bff-web-sockets-service
    ports:
      - 8083:8083
#    networks:
#      - mynet
    depends_on:
      - zipkin
  redis:
    image: redis:latest
    container_name: bff-redis
    ports:
      - 16379:6379
#    networks:
#      - mynet
  bff-frontend:
    image: frontend
    container_name: bff-frontend-service
    ports:
       - 8084:8084
#    networks:
#        - mynet
    depends_on:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
    ports:
      - 9411:9411
#    networks:
#      - mynet

#networks:
#  mynet:
