{
 "title": "Custom dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Endpoints execution time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "execution_duration_seconds_max" },
    {
     "expr": "rate(execution_duration_seconds_count[5m])"
    },
    {
     "expr": "rate(execution_duration_seconds_sum[5m])"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "request_count_total" }
   ]
  },
  {
   "title": "Errors count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "error_count_total\n" }
   ]
  }
 ]
}