#scrape_configs:
#  - job_name: cadvisor
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#          - cadvisor:8080
#          - bff-authors-service:8081
#          - bff-authors-service:8081/actuator/prometheus

scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['bff-authors-service:8081', 'bff-books-service:8082']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090','cadvisor:8080','node-exporter:9100' ]